# ==========================================
# IMPOSTAZIONI GLOBALI
# ==========================================
base_dir: "/content/drive/MyDrive/BDTM/gablation_studies"
n_runs: 2
num_examples: 3         # Metti -1 per usare l'intero dataset
force_reprocess: true   # Se true, sovrascrive le immagini anche se esistono già

skip_preprocessing: false  # Se true, salta completamente la generazione dei grafi
run_vlm: true              # Se false, si ferma dopo aver generatato le immagini

questions_path: "/content/MultipleChoice_mscoco_val2014_questions.json"
annotations_path: "/content/mscoco_val2014_annotations.json"
images_dir: "/content/val2014"

# Modelli VLM da confrontare
models:
  - "monodream"
  - "qwen2.5vl:3b"

# ==========================================
# GLI ESPERIMENTI (Studio Ablativo)
# ==========================================
experiments:
  
  ablate_edge_thickness:
    ablation_grid:
      rel_arrow_linewidth: [0.5, 3.0]
      
  ablate_max_relations_global:
    ablation_grid:
      max_relations: [4, 12,]

  ablate_max_relations_per_object:
    ablation_grid:
      max_relations_per_object: [0, 1, 2]

  ablate_edge_color:
    ablation_grid:
      edge_color: ["head", "tail", "neutral"]

  